// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJK5G07cMJe6v_XDMx9whY07e-uMBLtCk',
    appId: '1:907673353361:web:a42f865a2b9334268c5330',
    messagingSenderId: '907673353361',
    projectId: 'chargix-production',
    authDomain: 'chargix-production.firebaseapp.com',
    storageBucket: 'chargix-production.firebasestorage.app',
    measurementId: 'G-QB95G7Y6M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_Fetxrs57m_ldC6axCrnBkUQXw9AC8M',
    appId: '1:907673353361:android:8f203a575c0c0b188c5330',
    messagingSenderId: '907673353361',
    projectId: 'chargix-production',
    storageBucket: 'chargix-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmmlKxhvTtihIMcr3NlPA_lIaODJCKVJY',
    appId: '1:907673353361:ios:42be91f4c98b7fd78c5330',
    messagingSenderId: '907673353361',
    projectId: 'chargix-production',
    storageBucket: 'chargix-production.firebasestorage.app',
    iosBundleId: 'com.example.chargixProduction',
  );
}
