import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:chargix_production/app.dart';
import 'package:chargix_production/screens/splash/splash_screen.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Replace this import with your generated firebase_options.dart if present.
// If firebase_options.dart does not exist, remove the import and pass
// DefaultFirebaseOptions.currentPlatform to Firebase.initializeApp() once
// you run `flutterfire configure`.
// ─────────────────────────────────────────────────────────────────────────────
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait – adjust if landscape is needed
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Transparent status bar, light icons
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
    ),
  );

  // Initialise Firebase
  // If you have firebase_options.dart generated by flutterfire:
  //   await Firebase.initializeApp(
  //     options: DefaultFirebaseOptions.currentPlatform,
  //   );
  // Otherwise (options already baked into google-services.json):
  await Firebase.initializeApp();

  runApp(const ChargixEntryPoint());
}

/// Root entry widget.
///
/// Renders the [SplashScreen] first.  When the splash animation completes,
/// it replaces itself with [ChargixApp] (the real production shell) using a
/// smooth crossfade so there is no hard cut.
class ChargixEntryPoint extends StatefulWidget {
  const ChargixEntryPoint({super.key});

  @override
  State<ChargixEntryPoint> createState() => _ChargixEntryPointState();
}

class _ChargixEntryPointState extends State<ChargixEntryPoint> {
  bool _splashDone = false;

  void _onSplashComplete() {
    if (mounted) setState(() => _splashDone = true);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      // Black background prevents any white flicker during transition
      theme: ThemeData(
        scaffoldBackgroundColor: const Color(0xFF080B14),
        colorScheme: const ColorScheme.dark(),
      ),
      home: AnimatedSwitcher(
        duration: const Duration(milliseconds: 500),
        switchInCurve: Curves.easeIn,
        switchOutCurve: Curves.easeOut,
        transitionBuilder: (child, animation) =>
            FadeTransition(opacity: animation, child: child),
        child: _splashDone
            ? const ChargixApp()   // real production app
            : SplashScreen(        // premium animated splash
          key: const ValueKey('splash'),
          onComplete: _onSplashComplete,
        ),
      ),
    );
  }
}
